parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: nuliedu
    database_user: root
    database_password: '123456'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: aatycnm8xc00o48kc48w8oow444okkc
    webpack_base_url: http://www.nuliedu.com
    user_partner: none